
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viptxxzkugselyebxpfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpcHR4eHprdWdzZWx5ZWJ4cGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTc2NTgsImV4cCI6MjA2MzA3MzY1OH0.k-PDuGKJ6QDGYGjBTCd19QoQ-E7D9eO1pM7N47CFThk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
